Function update version 2.0

diff --git a/Executor/ConditionHandler b/Executor/ConditionHandler
--- a/Executor/ConditionHandler
+++ b/Executor/ConditionHandler
@@ -6,6 +6,8 @@
 #                                                                           #
 # This source code is licensed under the MIT license found in the           #
 # LICENSE file in the root directory of this source tree.                   #
+#############################################################################
+
 ############################## Parse Arguments ##############################
 
 # Set default values
@@ -77,56 +79,61 @@ cleanup_locks() {
 }
 
 decode_schedule() {
-# Usage: check_date <pattern>
-#  - <pattern> can be one of the following:
-#     - "always": Execute the function every time it is called.
-#     - "weekly: Mon, Tue, Wed, Thu, Fri, Sat, Sun": Execute the function on the specified days of the week.
-#       Replace the example days with your desired days.
-#     - "monthly: <day>": Execute the function on the specified day of the month.
-#       Replace <day> with the desired day of the month (e.g., "1" for the 1st day, "15" for the 15th day).
-#     - "never": Never execute the function.
     local sched=$1
-    local current_date=$(date +%F)                              # Get current date in YYYY-MM-DD format
+    local current_date=$(date +%F)
+    local current_day_of_week=$(date +%a)
+    local current_day_of_month=$(date +%d)
 
-    if [[ "$sched" == "always" ]]; then
-        return 0                                                # Match found, return true
+    case "$sched" in
+        "always")
+            echo "execute"
+            return 0
+            ;;
+        weekly:*)
+            # "weekly: Mon Tue Wed Thu Fri Sat Sun"
+            local days=${sched#weekly: }
+            if [[ "$days" == *"$current_day_of_week"* ]]; then
+                echo "execute"
+            else
+                echo "skip"
+            fi
+            return 0
+            ;;
+        monthly:*)
+            # "monthly: 1 15"
+            local days=${sched#monthly: }
+            for day in $days; do
+                if [[ "$current_day_of_month" -eq "$day" ]]; then
+                    echo "execute"
+                    return 0
+                fi
+            done
+            echo "skip"
+            return 0
+            ;;
+        "never")
+            echo "skip"
+            return 0
+            ;;
+        *)
+            echo "invalid"
+            return 0
+            ;;
+    esac
 
-    elif [[ "$sched" == weekly* ]]; then
-        local days="${sched#weekly: }"                       # Extract the days of the week
-        local current_day_of_week=$(date +%a)                   # Get current day of the week (e.g., Mon, Tue)
-
-        if [[ "$days" == *"$current_day_of_week"* ]]; then
-            return 0                                            # Match found, return true
-        fi
-
-    elif [[ "$sched" == monthly* ]]; then
-        local day_of_month="${sched#monthly: }"              # Extract the day of the month
-        local current_day_of_month=$(date +%d)                  # Get current day of the month
-
-        echo $current_day_of_month
-
-        if [[ "$current_day_of_month" -eq "$day_of_month" ]]; then
-            echo "Match found"
-            return 0                                            # Match found, return true
-        fi
-
-    elif [[ "$sched" == "never" ]]; then
-        return 99                                               # Match found, return "no execution code 99"
-    fi
-
-    return 1                                                    # No match found, return false
+    return 1
 }
 
 ################################## Jobs #####################################
 
 if [ "$task" == "evaluate" ] && [ "$type" == "execution" ]; then
     
-    if [[ -f "$marker_file" ]]; then          # Check if lock file exists
+    if [[ -f "$marker_file" ]]; then
         $NOTIFIER --channel "file"
         $NOTIFIER --channel "system" --args "normal" --message "$JOB_NAME: Mark for 'execution' is already set"
         exit 99
         
-    else                                    # Create lock file if none exists
+    else
         touch "$marker_file"
         $NOTIFIER --channel "file"
         $NOTIFIER --channel "file" --message "Create '$(basename "$marker_file")'"
@@ -152,19 +159,19 @@ elif [ "$task" == "evaluate" ] && [ "$type" == "lock" ]; then
         exit 99
     fi
 
-    decode_schedule "$schedule"
-    result=$?
-    if [ $result -eq 0 ] ; then
+    result=$(decode_schedule "$schedule")
+    
+    if [[ $result == "execute" ]] ; then
         touch "$marker_file"
         $NOTIFIER --channel "file"
         $NOTIFIER --channel "file" --message "Create '$(basename "$marker_file")'"
         exit 0
 
-    elif [ $result -eq 99 ]; then
+    elif [[ $result == "skip" ]]; then
         $NOTIFIER --channel "file"
         $NOTIFIER --channel "file" --message "Skipped '$process' due to the schedule '$schedule'"
         exit 99
-    else
+    elif [[ $result == "invalid" ]]; then
         $NOTIFIER --channel "system" --args "warning" --message "ERROR: $process schedule '$schedule' is no valid option"
         $NOTIFIER --channel "file" --message "Here are some examples of valid options:"
         $NOTIFIER --channel "file" --message "'always'"
@@ -172,7 +179,11 @@ elif [ "$task" == "evaluate" ] && [ "$type" == "lock" ]; then
         $NOTIFIER --channel "file" --message "'monthly: 12'"
         $NOTIFIER --channel "file" --message "'never'"
         exit 1
+    else
+        $NOTIFIER --channel "system" --args "warning" --message "ERROR: $JOB_NAME decode schedule '$schedule' faild"
+        exit 1
     fi
+    
     
 else
     $NOTIFIER --channel "system" --args "warning" --message "ERROR: $JOB_NAME ConditionHandler command unknown"
