Add Notify on finished flag. Update Notifier. Remove file extension.

diff --git a/Executor/ResticForgetExec b/Executor/ResticForgetExec
--- a/Executor/ResticForgetExec
+++ b/Executor/ResticForgetExec
@@ -1,5 +1,5 @@
 #!/bin/bash
-# BackupScripts version 1.0.2
+# BackupScripts version 1.0.3
 #################################### License ################################
 # MIT License Copyright (c) 2023 David Krumm                                #
 # All rights reserved.                                                      #
@@ -25,29 +25,31 @@ fi
 ################################## Funktions ################################
 
 call_notifier() {
-    local importance="$1"
-    local mes="$2"
-    "$home_path/Executor/Notifier.sh" "$home_path" "$job_name" "$importance" "$mes"
+    local channel="$1"
+    local args="$2"
+    local mes="$3"
+    "$home_path/Executor/Notifier" "$home_path" "$job_name" "$channel" "$args" "$mes"
 }
 
 evaluate_lock() {
     local lock_reason="forget"
-    "$home_path/Executor/LockHandler.sh" "$home_path" "check" "$job_name" "$lock_reason"
+    "$home_path/Executor/LockHandler" "$home_path" "check" "$job_name" "$lock_reason"
     exit_code=$?
     if [[ $exit_code -eq 99 ]]; then    # Lock file is set. Exit script normaly
         exit 0
     elif [[ $exit_code -ne 0 ]]; then   # Faild to evaluate. Exit with error
-        call_notifier "1" "ERROR $job_name: Failed to evaluate '$lock_reason'"
+        call_notifier "1" "" "ERROR $job_name: Failed to evaluate '$lock_reason'"
         exit 1
     fi                                  # No lock active. Lock has been set. Execution continues
 }
 
 release_lock() {
     local lock_reason="forget"
-    "$home_path/Executor/LockHandler.sh" "$home_path" "release" "$job_name" "$lock_reason"
+    "$home_path/Executor/LockHandler" "$home_path" "release" "$job_name" "$lock_reason"
     exit_code=$?
     if [[ "$exit_code" != 0 ]]; then    # Faild to evaluate. Exit with error
-        call_notifier "2" "ERROR $job_name: Failed to release '$lock_reason'"
+        call_notifier "1" "" "ERROR $job_name: Failed to release '$lock_reason'"
+        exit 1
     fi
 }
 
@@ -93,11 +95,11 @@ check_date() {
 
 # Check schedule for execution 
 if check_date "$schedule"; then     # Continue with the backup
-    call_notifier "1" ""
-    call_notifier "1" "Starting 'forget' job of '$repo'"
+    call_notifier "1" "" ""
+    call_notifier "1" "" "Starting 'forget' job of '$repo'"
 else                                # Stop execution
-    call_notifier "1" ""
-    call_notifier "1" "Skip 'forget' because of schedule '$schedule'"
+    call_notifier "1" "" ""
+    call_notifier "1" "" "Skip 'forget' because of schedule '$schedule'"
     release_lock                    # Release lock when scheduled day is over
     exit 0
 fi
@@ -111,25 +113,25 @@ cmd="docker run --rm --name $job_name-ResticForget \
     -r /repo forget $keep_rules"
 
 # progress message
-call_notifier "1" ""
-call_notifier "1" "Forget in progress ... "
-call_notifier "1" "Keep-Rules: '$keep_rules'"
-call_notifier "1" ""
-call_notifier "1" "$cmd"
+call_notifier "1" "" ""
+call_notifier "1" "" "Forget in progress ... "
+call_notifier "1" "" "Keep-Rules: '$keep_rules'"
+call_notifier "1" "" ""
+call_notifier "1" "" "$cmd"
 
 output=$(eval $cmd)
-call_notifier "-1" "$output"
+call_notifier "-1" "" "$output"
 exit_code=$?
 
 ################################# Evaluation ################################
 
 if [[ "$exit_code" == 0 ]]; then
-    call_notifier "1" ""
-    call_notifier "1" "Completed 'forget' job of '$repo' successfully"
+    call_notifier "1" "" ""
+    call_notifier "1" "" "Completed 'forget' job of '$repo' successfully"
     exit 0
 else
-    call_notifier "-1" ""
-    call_notifier "2" "ERROR $job_name:  Forget of '$repo' failed with exit_code=$exit_code"
-    call_notifier "-1" ""
+    call_notifier "-1" "" ""
+    call_notifier "1" "" "ERROR $job_name:  Forget of '$repo' failed with exit_code=$exit_code"
+    call_notifier "-1" "" ""
     exit 1
 fi
